### PR TITLE
New channel management and new option to remove individual channel

### PR DESCRIPTION
**Pull request by clementgarbay**
- Allow removing of individual channels
- Choice on icon sender
- Better channel management

### CODE REVIEW

**Comment by Dnomyar** [comment]
:+1:

**Comment by b-sharpe** [comment]
Great work Clement! I will give this a few days for review / last minute changes, and will merge into new release.

**Comment by clementgarbay** [comment]
Thanks to Anael too !

**Comment by b-sharpe** [comment]
My bad, Thanks Anael too! Sorry was looking on my phone at the time :smile: 
This is the first thing aside from a Hello World I've ever done in Java so really appreciate the community stepping up to help!

**Comment by anaelChardan** [comment]
I was crying ... XD, you're welcome, I'm not a Java developer too ^^, for an inexperience Java development you develop a very useful Plugin (with Clement we use it everyday at School) :)

**Comment by b-sharpe** [comment]
So I noticed this is now using Java 1.8. I ran into this issue when I first built it (which is why I was using 1.6 and avoiding lamda's, etc) where I could run the plugin, but nobody else could even with same versions of PHPStorm. I did some reading on this a while ago and I think the only reason it runs for us is because we have defined 1.8 as a source in our sources. 

I had a few colleagues try the new build (which I can run on IDEA and PHPStorm), and it installs but no menu icons show up at all. I'm gonna do some more testing, but if you have any ideas I'd love to sort this prior to merging into a new release.

**Comment by anaelChardan** [comment]
We updated the code at Java 1.6 but I don't understand your problem, Which version of PHPStorm do you use ? I use PHPStorm 10 and it works.

**Comment by b-sharpe** [comment]
You didn't have to rewrite it! :stuck_out_tongue:  

The problem is a bunch of colleagues can't get it to run when compiled as 1.8, yet they are all on PHPStorm 10 as well. I've been gathering info about what may be causing it.

I can run it both on Windows and Ubuntu in both IDEA and PHPStorm, so maybe not an issue at all and just something funky with their installs. I just didn't want to release it as a new release on jetbrains repo if there was an unknown. Gimme a few days here cause I would like to keep it at 1.8

_UPDATE_
Turns out I work with a bunch of liars! The ones who it wasn't working for are Ubuntu + PHPStorm 9 (141). I tested on my local and same here. I tested your latest update and it works, so for the sake of compatibility, let's keep your latest update. I am working on a quick fix tomorrow and then I will merge to new release. 

Again, thanks for your help

**Pull request merged**
